### PR TITLE
Swift Implementation

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
I found time to come back to this today. I will be able to work on it off and on, but I have realized it will involve a lot more dialogue, as there is a rapidly growing number of details in need clarification.

I made a draft pull request primarily to serve as a reminder for myself. If it were to just hide among my local files, I am more likely to forget about it. It would also make it easier for another developer to take over where I left off in the event you run out of patience with my pace.

Be aware that I expect to do a lot of squashing and force‐pushing on this branch until it is complete.

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
Question: Do you want it kept in a single file, or may I split the tests out and organize it as a conventional Swift project would?

**Comment by alextretyak** [comment]
> may I split the tests

What do you mean by ‘tests’ here? Just [this 9 lines of code in Python implementation](https://github.com/pqmarkup/pqmarkup-lite/blob/7d9bc7df692311ce4b964f3ddb17c06b8dcd933b/pqmarkup_lite.py#L415-L423)?

**Comment by SDGGiesbrecht** [comment]
Yes, those 9 lines. As they are, a single failure stops execution. Placed in a proper Swift test target instead, one failure wouldn’t prevent later tests from running, and the results would be tabulated nicely by the IDE.

**Comment by alextretyak** [comment]
> a single failure stops execution

That's ok. [I personally prefer fix errors one by one, so this behavior is by design.]

> Do you want it kept in a single file, or may I split the tests out and organize it as a conventional Swift project would?

Keep it in a single file, please.
I'd like to see how this 9 lines of Python code will be translated into Swift, rather than dive into details of Swift projects organization.

**Comment by alextretyak** [comment]
It looks like [Git supports placing .gitignore file into subfolders](https://essential-git.programming-books.io/ignoring-files-in-subfolders-multiple-gitignore-files-c9ae491ba25340c7aae9c052726b96ca).
Can you move your changes of the toplevel .gitignore file into new .gitignore file inside Swift folder?

**Comment by SDGGiesbrecht** [comment]
I moved the Swift‐specific `.gitignore` entries to their own directory.

I only added the separate tests for while I work. I will remove them again before you merge.

**Comment by SDGGiesbrecht** [comment]
I finally had time to come back and finish this.

The massive function length, cyclomatic complexity, and quirky initialization and recursion go against every bone in my body. But the two refactoring attempts I made (one as a clean, forward‐only loop, and the the other as a AST parser) ultimately failed due to inherent forward ambiguities in the the syntax design that seem to require backward retracing to resolve. Having failed to untangle it, I gave up and abandoned native strings altogether in favour of an array of Unicode scalars. Since an array’s indices are integers, I was then able to directly port the opaque, unchecked index math from the Python implementation. So in the end it does follow the Python implementation very closely.

I have removed the various other files I used while I was working. All that remains are the standard files for building, and the .gitignore additions for macOS and Swift.

All tests pass.

**Comment by alextretyak** [comment]
Oh, sorry!
I totally missed your last comment/commit.

> All tests pass.

Great thanks for your work!

But there is also an [i.data file](https://github.com/pqmarkup/pqmarkup-lite/blob/master/i.data) in pqmarkup-lite repository, which is used for thorough testing. Any proper pqmarkup-lite implementation should generate the same output as Python version (i.e. after executing commands `python pqmarkup_lite.py i.data out.html` and `your_implementation i.data out2.html`, files `out.html` and `out2.html` should be the same).

Your implementation almost correctly process an i.data file, but a couple fixes (68ca3b6ee568a17afa410b0f836600dd5fe92892) were required to perform processing perfectly.

I have some questions regarding your implementation (sorry if some of them are stupid):
- Why `func split<S>(...)` and `func splitAtFirst<S>(..)` are needed? Why not use standard `split` method?
- What are extensions `DefaultStringInterpolation` and `RangeReplaceableCollection` for?
- Why `findQuotationMark()` returns `Array<Unicode.Scalar>.SubSequence`, but not just integer index?

Also I'm writing an article devoted to comparison of different implementations of pqmarkup-lite.
Can you tell anything interesting about your implementation?

**Comment by SDGGiesbrecht** [comment]
> Your implementation almost correctly process an i.data file, but a couple fixes (68ca3b6) were required to perform processing perfectly.

Yes, good catch.

I think the `+ 1` should not apply to the right hand side of `??` though. Python’s `rfind` yields the beginning of the slash or −1 if there is none. Adding one moves it the end of the slash or 0. But Swift yields `nil` instead of −1 (which is not an instantiable index for most collections), and here `nil` falls back to `startIndex` (i.e. 0). So the `+ 1` applied to both branches yields the end of the slash or 1—dropping the first character if the right hand branch is taken, and potentially reaching out of bounds. How about this instead?:

```swift
if let slash = link.prefix(47).lastIndex(of: "/") {
  link = "\(link[...slash])..." // Up to and including the slash.
} else {
  link = "..." // Up to the start index would be empty anyway by definition.
}
```

> Why `func split<S>(...)` and `func splitAtFirst<S>(...)` are needed? Why not use standard split method?

The standard library provides a `split` function, but it splits on singular _elements_. It doesn’t provide a function that splits on _subsequences_ of arbitrary length, which is what is implemented here.

> What are extensions DefaultStringInterpolation and RangeReplaceableCollection for?

These allow expressing other types in the source code with string literals. Without those conformances, lines like this would need to have been written in more awkward ways:

```swift
// Because...
var endingTags: [[Unicode.Scalar]] = []

// ...with the literal and interpolation protocols:
endingTags.append("</\(tag)>")

// ...without the literal and interpolation protocols:
endingTags.append([["<", "/"], Array(tag), [">"]].joined())
```

> Why findQuotationMark() returns Array<Unicode.Scalar>.SubSequence, but not just integer index?

Subsequences are designed to be efficient. Usually they are just references into a portion of the parent’s memory. That makes them nearly as cheap to store and manipulate as the indices that define them.

In pqmarkup, the calling code of the `find...` methods often wants to use information about where the find _ends_. This is more straightforward if the find itself was returned as a subsequence instead of only having been reported as a starting point. Locating the end is then just `foundSubsequence.endIndex` instead of `collection.index(foundStartingPoint, offsetBy: lengthOfSearchTerm)`.

**Comment by alextretyak** [comment]
> I think the `+ 1` should not apply to the right hand side of `??` though.

In this case it does not matter, because `link` always has `/` in it (valid link starts with `http://`, `https://`, or `./`), so `lastIndex(of: "/")` will never return `nil`.

**Comment by alextretyak** [comment]
I have made some performance tests, and Swift implementation was rather slow: it was just 2 times faster than Python, and 12 times slower than C++ UTF-8 implementation.
I compiled Swift code with `-O` flag. [Without `-O` flag execution time is 6 times more than with it (i.e. 3 times slower than Python).]
Maybe I missed something?

**Comment by SDGGiesbrecht** [comment]
I am not entirely surprised. There are a lot of conversions happening between `String` and `[Unicode.Scalar]`, because the loaded file and all the source literals start out as strings, but then are converted to arrays for processing and eventually converted back again. Each conversion needs to allocate new memory.

Swift is deliberately designed to make several things we are doing here repellent. For example, its type system ensures string indices cannot be used as integers. A string of length 1 concatenated with another string of length 1 may still just be of length 1. So all the + 1, − 1 stuff we do here is seen as an unsafe bad practice. Also, the parsing style Swift makes easy is one‐way (because the back‐and‐forth we do here is inefficient, as each attempt to walk to another index is O(n)). Dodging these guide rails in order to mimic Python’s logic flow brought a performance cost with it.

If someone can implement the whole thing from scratch, it would probably be both much faster and radically different. My first two attempts were along those lines, but the Python implementation’s interacting parts were to many and too far apart from one another for me to be able to follow what they are doing at times.

Instead, the final implementation was made by copying and pasting the Python file, prepending any expected methods under their Python names, adjusting the syntax until it would compile, and then gradually renaming and refactoring small pieces until it felt like (mostly) natural Swift. None of the individual refactors reached beyond a dozen or so lines of context, because at that point I would start to get lost. Every refactoring attempt I made that was broader than that ended up introducing errors, so I had to walk those ones back.

You are welcome to find another Swift developer to give a crack at it and see if they can do better. I will not be offended.

**Pull request merged**
